[[redirects]]
from="/2022/02/24/introduction-to-html/"
to="/blogs/introduction-to-html/1645744806/"

[[redirects]]
from="/2022/02/19/introduction-to-web-development/"
to="/blogs/introduction-to-web-development/1686525497/"

[[redirects]]
from="/2022/02/19/disclaimer/"
to="/blogs/disclaimer/1645312806/"

[[redirects]]
from="/2022/03/05/introduction-to-css/"
to="/blogs/introduction-to-css/1646522406/"

[[redirects]]
from="2022/06/09/brief-introduction-to-flexbox-part-1/"
to="/blogs/introduction-to-web-development/1686525497/#flexbox"

[[redirects]]
from="2022/06/09/brief-introduction-to-flexbox-part-2/"
to="/blogs/introduction-to-web-development/1686525497/#flexbox"

[[redirects]]
from="2022/06/09/brief-introduction-to-flexbox-part-3/"
to="/blogs/introduction-to-web-development/1686525497/#flexbox"
