name: Jekyll site CI

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - name: Checkout with actions/checkout@v3
        uses: actions/checkout@v3

      - name: Setup with actions/setup-node@v3 to use node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build the site in the jekyll/builder container
        run: |
          npm install
          npm run build

      - name: Build and Deploy with JamesIves/github-pages-deploy-action@v4
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist
