name: Jekyll site CI

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - name: Checkout with actions/checkout@v3
        uses: actions/checkout@v3

      - name: Build the site in the jekyll/builder container
        run: |
          npm install
          npm run build

      - name: Build and Deploy with JamesIves/github-pages-deploy-action@v4
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist
