name: Jekyll site CI

on:
  pull_request:
    types: [closed]
    branches: [master]


jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: echo "NET_ENV\":\" $NET_ENV"
      - run: npm ci
      - run: |
          node ./bin/create-meta.js && \
          VITE_DCMA=$VITE_DCMA \
          VITE_GA4=$VITE_GA4 \
          VITE_GTM=$VITE_GTM \
          npx qwik build
      - run: npm test

      - name: Build and Deploy with JamesIves/github-pages-deploy-action@v4
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist
