name: Jekyll site CI

on:
  pull_request:
    types: [closed]
    branches: [master]


jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: ./scripts/lint.sh
      - run: ./scripts/test.sh
      - run: ./scripts/pre-build.sh
      - run: |
          VITE_DCMA=${{ vars.VITE_DCMA }} \
          VITE_GA4=${{ vars.VITE_GA4 }} \
          VITE_GTM=${{ vars.VITE_GTM }} \
          npx qwik build

      - name: Build and Deploy with JamesIves/github-pages-deploy-action@v4
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ssh-key: ${{ secrets.GH_PAGE_DEPLOY_TOKEN }}
          branch: gh-pages
          folder: dist
